import {
  SFA_COMPREHENSIVE_FILTERS,
  SFA_COMPREHENSIVE_GUIDELINES_VERSION,
  SFA_COMPREHENSIVE_OUTLINE,
  SFA_COMPREHENSIVE_DESIGN,
  SFA_COMPREHENSIVE_QUALITY,
  SFA_COMPREHENSIVE_ROLE_POLICY,
  SFA_COMPREHENSIVE_VERIFY,
} from "./comprehensive-guidelines";
import { STUDENT_FILL_REPORT_RESULT_METRICS } from "./generation-guidelines";

export function buildStudentFillComprehensiveGuidelines(analysisYear: number): string {
  const from = analysisYear - 4;
  return [
    "═══════════════════════════════════════════════════════════",
    "  K-UniTrust · 학생충원분석 종합보고서 생성 지침",
    `  버전 ${SFA_COMPREHENSIVE_GUIDELINES_VERSION} · 분석연도 ${analysisYear}년`,
    "═══════════════════════════════════════════════════════════",
    "",
    "■ 0. 목적",
    "",
    `· ${analysisYear}년 분석결과의 대표본교 집단을 한 부의 8장 심층 분석 보고서로 만든다.`,
    `· 매년 같은 목차·표·차트 구성과 같은 검증 절차로, ${from}–${analysisYear}년(5개년) 고품질 보고서를 반복 생성한다.`,
    "· 분교·캠퍼스 인원을 본교에 합산한 뒤 율·비중을 재계산한다. 캠퍼스를 빼거나 캠퍼스 율을 평균하지 않는다.",
    "",
    "■ 1. 생성 전 검증 (필수 · 생략 불가)",
    "",
    ...SFA_COMPREHENSIVE_VERIFY.map((line) => `· ${line}`),
    "",
    "  [검증 실패 시 화면 안내 예]",
    "  · 오류: 「2026년 외국인 인원이 전원 비어 있습니다. 분석실행을 다시 하세요.」→ 생성 중단",
    "  · 주의: 「외국인 인원 공시 291/313교. 교대·간호 등 미공시는 0으로 넣지 않습니다.」→ 안내 후 생성 가능",
    "  · 주의: 「모집인원이 0이라 충원율을 계산하지 않은 본교(부산예술대). 0%로 채우지 않습니다.」",
    "",
    "■ 2. 분석조건 필터",
    "",
    ...SFA_COMPREHENSIVE_FILTERS.map((item) => `· ${item.label}: ${item.rule}`),
    "",
    "■ 3. 운영·저장·PDF",
    "",
    "· 화면 본문은 검증을 통과한 종합보고서 HTML이다.",
    "· 저장 위치: data/json/student-fill-analysis/{연도}/comprehensive/{연도}_{권역}_{설립}_{학제}.json",
    "· 같은 키로 다시 저장하면 덮어쓴다.",
    "",
    "  [관리자]",
    ...SFA_COMPREHENSIVE_ROLE_POLICY.admin.map((line) => `  · ${line}`),
    "",
    "  [사용자]",
    ...SFA_COMPREHENSIVE_ROLE_POLICY.user.map((line) => `  · ${line}`),
    "",
    "■ 4. 고정 목차 (매년 동일)",
    "",
    ...SFA_COMPREHENSIVE_OUTLINE.map((item) => `  ${item.order}. ${item.title}`),
    "",
    "■ 5. 반드시 넣을 지표",
    "",
    "  표·차트 숫자는 분석실행(본교 합산)과 일치해야 한다. 시안·첨부 PDF 숫자를 복사하지 않는다.",
    "  [신입생]",
    ...STUDENT_FILL_REPORT_RESULT_METRICS.freshman.map((item) => `    · ${item.label}`),
    "  [재학생]",
    ...STUDENT_FILL_REPORT_RESULT_METRICS.enrolled.map((item) => `    · ${item.label}`),
    "  [외국인]",
    ...STUDENT_FILL_REPORT_RESULT_METRICS.foreign.map((item) => `    · ${item.label}`),
    "",
    "■ 6. 품질 규칙 (매년 동일 수준)",
    "",
    ...SFA_COMPREHENSIVE_QUALITY.map((line) => `· ${line}`),
    "",
    `■ 7. A4 서식 · 디자인 표준 v2.2 (${analysisYear}년)`,
    "",
    ...SFA_COMPREHENSIVE_DESIGN.map((line) => `· ${line}`),
    "· 열람: HTML. 인쇄 / PDF 저장(Ctrl+P, 세로, 배경 그래픽 켜기).",
    "",
  ].join("\n");
}
