import {
  STUDENT_FILL_REPORT_ACTION_RULES,
  STUDENT_FILL_REPORT_GUIDELINES_VERSION,
  STUDENT_FILL_REPORT_INTERPRETATION_RULES,
  STUDENT_FILL_REPORT_OUTLINE,
  STUDENT_FILL_REPORT_PRIORITY,
  STUDENT_FILL_REPORT_ROLE_POLICY,
  STUDENT_FILL_REPORT_WRITING_EXAMPLE,
} from "./generation-guidelines";

/** 분석연도가 찍힌 개별대학 보고서 작성지침 전문 */
export function buildStudentFillReportGuidelines(analysisYear: number): string {
  const ex = STUDENT_FILL_REPORT_WRITING_EXAMPLE;
  const lines: string[] = [
    "═══════════════════════════════════════════════════════════",
    "  K-UniTrust · 학생충원분석 개별대학 보고서 작성 지침",
    `  버전 ${STUDENT_FILL_REPORT_GUIDELINES_VERSION} · 분석연도 ${analysisYear}년`,
    "═══════════════════════════════════════════════════════════",
    "",
    "■ 0. 운영·권한",
    "",
    "· 보고서는 분석연도(에디션) 단위로 대학별 생성·보관한다.",
    "· 선행 조건: 해당 연도 분석실행이 끝나 저장본이 있어야 한다.",
    "",
    "  [관리자]",
    ...STUDENT_FILL_REPORT_ROLE_POLICY.admin.map((line) => `  · ${line}`),
    "",
    "  [사용자]",
    ...STUDENT_FILL_REPORT_ROLE_POLICY.user.map((line) => `  · ${line}`),
    "",
    "■ 1. 고정 목차 (모든 대학 동일 순서)",
    "",
    ...STUDENT_FILL_REPORT_OUTLINE.map(
      (item) => `  ${item.order}. ${item.title}`,
    ),
    "",
    "■ 2. 교차분석 규칙 — 사실 나열 금지",
    "",
    ...STUDENT_FILL_REPORT_INTERPRETATION_RULES.map((line) => `· ${line}`),
    "",
    "■ 3. 핵심진단 작성",
    "",
    "· 진단은 지표 나열이 아니라 「이 대학이 직면한 문제」를 제목으로 쓴다.",
    "· 심각(crisis): 모집 분모 착시, 1학년 누수가 재학생충원의 선행지표일 때.",
    "· 경고(warn): 정원내 재학 공동화, 휴학 과다, 유학생 언어 부실.",
    "· 단계 라벨(충원보통 등)을 결론으로 쓰지 말고, 라벨이 가리는 구조를 결론으로 쓴다.",
    "· 이사회용 한 줄 요약을 제4부 끝에 넣는다. 숫자 3개 이하로 핵심 과제를 고정한다.",
    "",
    "■ 4. 대응과제 작성",
    "",
    ...STUDENT_FILL_REPORT_ACTION_RULES.map((line) => `· ${line}`),
    "",
    "■ 5. 우선순위",
    "",
    ...STUDENT_FILL_REPORT_PRIORITY.map((line) => `· ${line}`),
    "",
    "■ 6. 서술 예시 (특정 대학 고정 금지 — 논리만 이식)",
    "",
    `  예) ${ex.year}년 ${ex.schoolName} (경남·동남권·소규모 사립).`,
    `  한 줄: ${ex.oneLiner}`,
    ...ex.notes.map((note) => `  · ${note}`),
    "  · 과제 골격: 모집총량 동결+학과 재배분 / Freshman 8주 출석·튜터 / 휴학 전수 복학 / 정원외 학과 캡 / 유학 모집 잠금+집중어학.",
    "  · 위 학교는 예시이다. 생성 결과는 해당 대학 수치로만 채운다.",
    "",
    "■ 7. HTML·PDF",
    "",
    "· 표지: 학교명, 분석연도, 시·도·권역, 재학생·규모·설립, 충원단계, 정원내외 충원율, 재학생충원(내외/정원내), 신입탈락·휴학.",
    "· 제1부: 교차 통찰 카드(착시·공동화·누수·휴학·외국인 중 해당 항목만).",
    "· 제2부: 심각/경고 진단.",
    "· 제3부: 과제별 주관·예산·성과지표·기대효과.",
    "· 제4부: 연간 현금 합계와 우선순위. 지침 버전을 각주에 표기한다.",
    "",
  ];
  return lines.join("\n");
}
