import {
  STUDENT_FILL_REPORT_ACTION_RULES,
  STUDENT_FILL_REPORT_FORMAT_RULES,
  STUDENT_FILL_REPORT_GUIDELINES_VERSION,
  STUDENT_FILL_REPORT_INTERPRETATION_RULES,
  STUDENT_FILL_REPORT_OUTLINE,
  STUDENT_FILL_REPORT_PRIORITY,
  STUDENT_FILL_REPORT_RESULT_METRICS,
  STUDENT_FILL_REPORT_ROLE_POLICY,
  STUDENT_FILL_REPORT_WRITING_EXAMPLE,
} from "./generation-guidelines";

function metricLine(
  stage: keyof typeof STUDENT_FILL_REPORT_RESULT_METRICS,
  title: string,
): string[] {
  return [
    `  [${title}]`,
    ...STUDENT_FILL_REPORT_RESULT_METRICS[stage].map(
      (item) => `    · ${item.label}`,
    ),
  ];
}

/** 분석연도가 찍힌 개별대학 보고서 생성지침 전문 */
export function buildStudentFillReportGuidelines(analysisYear: number): string {
  const ex = STUDENT_FILL_REPORT_WRITING_EXAMPLE;
  const bodyOutline = STUDENT_FILL_REPORT_OUTLINE.filter(
    (item) => item.id !== "cover",
  );
  return [
    "═══════════════════════════════════════════════════════════",
    "  K-UniTrust · 학생충원분석 개별대학 보고서 생성 지침",
    `  버전 ${STUDENT_FILL_REPORT_GUIDELINES_VERSION} · 분석연도 ${analysisYear}년`,
    "═══════════════════════════════════════════════════════════",
    "",
    "■ 0. 목적",
    "",
    `· ${analysisYear}년 대학별분석 「분석결과」에 나온 숫자를 보고서에 모두 담는다.`,
    "· 진단은 시계열(최근 5년)과 권역·규모·설립·시도 평균 대비 본교 위치를 쉬운 말로 적는다.",
    "· 대응전략은 그 진단에서 나온 약한 곳만, 현장에서 바로 할 수 있는 일로 적는다.",
    "· 서식은 대학별경쟁력·대학별추계와 같은 A4 양식이다. 열람은 별도 창이다.",
    "",
    "■ 1. 운영·권한",
    "",
    "· 선행 조건: 해당 연도 분석실행이 끝나 저장본이 있어야 한다.",
    "",
    "  [관리자]",
    ...STUDENT_FILL_REPORT_ROLE_POLICY.admin.map((line) => `  · ${line}`),
    "",
    "  [사용자]",
    ...STUDENT_FILL_REPORT_ROLE_POLICY.user.map((line) => `  · ${line}`),
    "",
    "■ 2. 고정 목차 (모든 대학 동일)",
    "",
    "  표지 — 표지·기본정보",
    ...bodyOutline.map((item, index) => `  ${index + 1}쪽 — ${item.title}`),
    "",
    "■ 3. 제1부 분석결과 — 반드시 넣을 지표",
    "",
    "· 대학별분석 분석결과 탭과 같은 지표를 모두 넣는다.",
    "· 파트마다 표 쪽과 차트 쪽을 둔다.",
    "· 표 쪽: ①본교 5개년 표 ②당해 연도 권역·규모·설립·시도·전국 평균 비교표.",
    "· 차트 쪽: 해당 파트 전 지표의 시계열만 넣는다. 각 지표마다 본교·권역·규모·전국 동종 선을 그린다.",
    "· 권역별·학생규모별 막대 차트는 넣지 않는다.",
    "",
    ...metricLine("freshman", "신입생충원"),
    ...metricLine("enrolled", "재학생충원"),
    ...metricLine("foreign", "외국인"),
    "",
    "■ 4. 제2부 진단 — 반드시 답할 질문",
    "",
    "· 각 지표의 5개년 추세는 증가인가, 감소인가, 비슷한가.",
    "· 권역 평균 대비 본교는 높은가, 낮은가, 비슷한가.",
    "· 같은 학생규모 평균 대비 본교 위치는 어떠한가.",
    "· 같은 시도 평균 대비 본교는 어떠한가. 설립구분 평균과도 비교한다.",
    "· 신입생: 정원내충원율과 정원내외충원율은 어떠한가. 정원외비중은 늘고 있는가, 줄고 있는가.",
    "· 신입생탈락율은 중도탈락율보다 높은가, 낮은가.",
    "· 재학생: 재학생충원율과 정원내충원율은 어떠한가. 정원외비중은 어떠한가.",
    "· 휴학비중·유예비중은 권역·규모·설립·시도 평균보다 높은가.",
    "· 외국인: 재적대비비중은 늘고 있는가. 언어능력충족율은 집단 평균과 비교해 어떠한가.",
    "· 전체외국인탈락율은 어떠한가. 외국인탈락율(학위)과 구분해 적는다.",
    "",
    ...STUDENT_FILL_REPORT_INTERPRETATION_RULES.map((line) => `· ${line}`),
    "",
    "■ 5. 제3부 대응전략 — 쉽게",
    "",
    ...STUDENT_FILL_REPORT_ACTION_RULES.map((line) => `· ${line}`),
    "",
    "■ 6. 우선순위",
    "",
    ...STUDENT_FILL_REPORT_PRIORITY.map((line) => `· ${line}`),
    "",
    "■ 7. 서술 방향 (특정 대학 고정 금지)",
    "",
    `  예) ${ex.year}년 ${ex.schoolName}은 숫자 예시일 뿐이다.`,
    `  ${ex.oneLiner}`,
    "  생성 결과는 해당 대학의 분석결과·집단 평균만 사용한다.",
    "",
    `■ 8. A4 서식 (${analysisYear}년)`,
    "",
    ...STUDENT_FILL_REPORT_FORMAT_RULES.map((line) => `· ${line}`),
    "",
  ].join("\n");
}
