import {
  SFA_COMPREHENSIVE_FILTERS,
  SFA_COMPREHENSIVE_GUIDELINES_VERSION,
  SFA_COMPREHENSIVE_OUTLINE,
  SFA_COMPREHENSIVE_ROLE_POLICY,
  SFA_COMPREHENSIVE_RULES,
} from "./comprehensive-guidelines";
import { STUDENT_FILL_REPORT_RESULT_METRICS } from "./generation-guidelines";

export function buildStudentFillComprehensiveGuidelines(analysisYear: number): string {
  return [
    "═══════════════════════════════════════════════════════════",
    "  K-UniTrust · 학생충원분석 종합보고서 생성 지침",
    `  버전 ${SFA_COMPREHENSIVE_GUIDELINES_VERSION} · 분석연도 ${analysisYear}년`,
    "═══════════════════════════════════════════════════════════",
    "",
    "■ 0. 목적",
    "",
    `· ${analysisYear}년 분석결과 화면의 분석조건으로 고른 대학 집단을 한 부의 종합보고서로 만든다.`,
    "· 개별대학 보고서와 달리, 학교 하나가 아니라 필터에 걸린 대학의 가중 집계를 적는다.",
    "· 보고서는 매년 생성하고, 생성된 본문은 저장한다. PDF로도 남길 수 있다.",
    "",
    "■ 1. 분석조건 필터 (보고서 범위를 정한다)",
    "",
    ...SFA_COMPREHENSIVE_FILTERS.map((item) => `· ${item.label}: ${item.rule}`),
    "",
    "· 필터를 바꾸면 KPI·표·차트·진단 문장을 그 집단으로 다시 계산한다.",
    "· 「전체 추이」가 아니라 선택한 분석연도를 표지의 기준 연도로 쓴다. 시계열만 최근 5년을 붙인다.",
    "",
    "■ 2. 운영·저장·PDF",
    "",
    "· 화면 본문은 첨부 종합보고서 HTML이다. 분석조건 필터는 보고서 상단 네 개 선택상자다.",
    "· 저장 위치: data/json/student-fill-analysis/{연도}/comprehensive/{연도}_{권역}_{설립}_{학제}.json",
    "· 같은 키로 다시 저장하면 덮어쓴다.",
    "",
    "  [관리자]",
    ...SFA_COMPREHENSIVE_ROLE_POLICY.admin.map((line) => `  · ${line}`),
    "",
    "  [사용자]",
    ...SFA_COMPREHENSIVE_ROLE_POLICY.user.map((line) => `  · ${line}`),
    "",
    "■ 3. 고정 목차",
    "",
    ...SFA_COMPREHENSIVE_OUTLINE.map((item) => `  ${item.order}. ${item.title}`),
    "",
    "■ 4. 반드시 넣을 지표",
    "",
    "  첨부 보고서와 동일: 정원내충원율, 정원외·모집증감, 신입생탈락율, 재학생충원율, 중도탈락율, 외국인 비중·언어충족율·이탈률.",
    "  제1~3장 뒤에 국공립·사립, 수도권·비수도권, 대학·전문대학, 선제 정원감축 권역 비교를 이어 적는다.",
    "  [참고 지표]",
    ...STUDENT_FILL_REPORT_RESULT_METRICS.freshman.map((item) => `    · ${item.label}`),
    ...STUDENT_FILL_REPORT_RESULT_METRICS.enrolled.map((item) => `    · ${item.label}`),
    ...STUDENT_FILL_REPORT_RESULT_METRICS.foreign.map((item) => `    · ${item.label}`),
    "",
    "■ 5. 작성 규칙",
    "",
    ...SFA_COMPREHENSIVE_RULES.map((line) => `· ${line}`),
    "",
    `■ 6. A4 서식 (${analysisYear}년)`,
    "",
    "· 용지: A4 가로. 첨부 종합보고서 서식을 유지한다.",
    "· 열람: HTML. 인쇄 / PDF 저장(Ctrl+P, 가로).",
    "",
  ].join("\n");
}